In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pylab as pl
import os
%pylab inline

Populating the interactive namespace from numpy and matplotlib

# Download and clean NYC anual crime data

In [14]:
df = pd.read_excel("https://www1.nyc.gov/assets/nypd/downloads/excel/analysis_and_planning/seven-major-felony-offenses-2000-2016.xls")

In [19]:
os.getenv("PUIDATA")

'/Users/andrewchen/PUIDATA'

In [22]:
df.to_csv(os.getenv("PUIDATA")+'/crime.csv', encoding='utf-8')

In [23]:
ad = pd.read_csv(os.getenv("PUIDATA")+'/crime.csv')

In [25]:
ad = np.transpose(ad)

In [26]:
ad

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
Seven Major Felony Offenses,NaN,NaN,OFFENSE,MURDER & NON-NEGL. MANSLAUGHTER,RAPE,ROBBERY,FELONY ASSAULT,BURGLARY,GRAND LARCENY,GRAND LARCENY OF MOTOR VEHICLE,TOTAL SEVEN MAJOR FELONY OFFENSES,NaN,NaN,STATISTICAL NOTES,1. 2000-2005 Data Source-Historical Comfinal d...,2. 2006-2016 Data Source-CDW Omniform System a...,3. Murder & Non-Negligent Manslaughter data so...,4. 2000-2009 data as of 12/8/2010. 2010 data ...
Unnamed: 1,NaN,NaN,2000,673,2068,32562,25924,38352,49631,35442,184652,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 2,NaN,NaN,2001,649,1981,28202,23453,32763,46329,29531,162908,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 3,NaN,NaN,2002,587,2144,27229,21147,31275,45771,26656,154809,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 4,NaN,NaN,2003,597,2070,25989,19139,29110,46751,23413,147069,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 5,NaN,NaN,2004,570,1905,24373,18622,26976,48763,20884,142093,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 6,NaN,NaN,2005,539,1858,24722,17750,24117,48243,18246,135475,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 7,NaN,NaN,2006,596,1525,23739,17309,23143,46625,15745,128682,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 8,NaN,NaN,2007,496,1351,21809,17493,21762,44924,13174,121009,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 9,NaN,NaN,2008,523,1299,22401,16284,20725,44242,12482,117956,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 10,NaN,NaN,2009,471,1205,18601,16773,19430,39580,10670,106730,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 11,NaN,NaN,2010,536,1373,19486,16956,18600,37835,10329,105115,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 12,NaN,NaN,2011,515,1420,19717,18482,18720,38501,9314,106669,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 13,NaN,NaN,2012,419,1445,20144,19381,19168,42497,8093,111147,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 14,NaN,NaN,2013,335,1378,19128,20297,17429,45368,7400,111335,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 15,NaN,NaN,2014,333,1352,16539,20207,16765,43862,7664,106722,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 16,NaN,NaN,2015,352,1438,16931,20270,15125,44005,7332,105453,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 17,NaN,NaN,2016,335,1438,15500,20847,12990,44279,6327,101716,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
crime = ad.iloc[1:19,2:11]

In [45]:
crime

,2,3,4,5,6,7,8,9,10
Seven Major Felony Offenses,OFFENSE,MURDER & NON-NEGL. MANSLAUGHTER,RAPE,ROBBERY,FELONY ASSAULT,BURGLARY,GRAND LARCENY,GRAND LARCENY OF MOTOR VEHICLE,TOTAL SEVEN MAJOR FELONY OFFENSES
Unnamed: 1,2000,673,2068,32562,25924,38352,49631,35442,184652
Unnamed: 2,2001,649,1981,28202,23453,32763,46329,29531,162908
Unnamed: 3,2002,587,2144,27229,21147,31275,45771,26656,154809
Unnamed: 4,2003,597,2070,25989,19139,29110,46751,23413,147069
Unnamed: 5,2004,570,1905,24373,18622,26976,48763,20884,142093
Unnamed: 6,2005,539,1858,24722,17750,24117,48243,18246,135475
Unnamed: 7,2006,596,1525,23739,17309,23143,46625,15745,128682
Unnamed: 8,2007,496,1351,21809,17493,21762,44924,13174,121009
Unnamed: 9,2008,523,1299,22401,16284,20725,44242,12482,117956
Unnamed: 10,2009,471,1205,18601,16773,19430,39580,10670,106730
Unnamed: 11,2010,536,1373,19486,16956,18600,37835,10329,105115
Unnamed: 12,2011,515,1420,19717,18482,18720,38501,9314,106669
Unnamed: 13,2012,419,1445,20144,19381,19168,42497,8093,111147
Unnamed: 14,2013,335,1378,19128,20297,17429,45368,7400,111335
Unnamed: 15,2014,333,1352,16539,20207,16765,43862,7664,106722
Unnamed: 16,2015,352,1438,16931,20270,15125,44005,7332,105453
Unnamed: 17,2016,335,1438,15500,20847,12990,44279,6327,101716

In [47]:
crime.columns = crime.iloc[0,:]

In [49]:
crime = crime.iloc[1:18,:]

In [56]:
crime

Seven Major Felony Offenses,OFFENSE,MURDER & NON-NEGL. MANSLAUGHTER,RAPE,ROBBERY,FELONY ASSAULT,BURGLARY,GRAND LARCENY,GRAND LARCENY OF MOTOR VEHICLE,TOTAL SEVEN MAJOR FELONY OFFENSES
Unnamed: 1,2000,673,2068,32562,25924,38352,49631,35442,184652
Unnamed: 2,2001,649,1981,28202,23453,32763,46329,29531,162908
Unnamed: 3,2002,587,2144,27229,21147,31275,45771,26656,154809
Unnamed: 4,2003,597,2070,25989,19139,29110,46751,23413,147069
Unnamed: 5,2004,570,1905,24373,18622,26976,48763,20884,142093
Unnamed: 6,2005,539,1858,24722,17750,24117,48243,18246,135475
Unnamed: 7,2006,596,1525,23739,17309,23143,46625,15745,128682
Unnamed: 8,2007,496,1351,21809,17493,21762,44924,13174,121009
Unnamed: 9,2008,523,1299,22401,16284,20725,44242,12482,117956
Unnamed: 10,2009,471,1205,18601,16773,19430,39580,10670,106730
Unnamed: 11,2010,536,1373,19486,16956,18600,37835,10329,105115
Unnamed: 12,2011,515,1420,19717,18482,18720,38501,9314,106669
Unnamed: 13,2012,419,1445,20144,19381,19168,42497,8093,111147
Unnamed: 14,2013,335,1378,19128,20297,17429,45368,7400,111335
Unnamed: 15,2014,333,1352,16539,20207,16765,43862,7664,106722
Unnamed: 16,2015,352,1438,16931,20270,15125,44005,7332,105453
Unnamed: 17,2016,335,1438,15500,20847,12990,44279,6327,101716

In [64]:
crime=crime.rename(columns = {'OFFENSE':'Year'})

In [65]:
crime

Seven Major Felony Offenses,Year,MURDER & NON-NEGL. MANSLAUGHTER,RAPE,ROBBERY,FELONY ASSAULT,BURGLARY,GRAND LARCENY,GRAND LARCENY OF MOTOR VEHICLE,TOTAL SEVEN MAJOR FELONY OFFENSES
Unnamed: 1,2000,673,2068,32562,25924,38352,49631,35442,184652
Unnamed: 2,2001,649,1981,28202,23453,32763,46329,29531,162908
Unnamed: 3,2002,587,2144,27229,21147,31275,45771,26656,154809
Unnamed: 4,2003,597,2070,25989,19139,29110,46751,23413,147069
Unnamed: 5,2004,570,1905,24373,18622,26976,48763,20884,142093
Unnamed: 6,2005,539,1858,24722,17750,24117,48243,18246,135475
Unnamed: 7,2006,596,1525,23739,17309,23143,46625,15745,128682
Unnamed: 8,2007,496,1351,21809,17493,21762,44924,13174,121009
Unnamed: 9,2008,523,1299,22401,16284,20725,44242,12482,117956
Unnamed: 10,2009,471,1205,18601,16773,19430,39580,10670,106730
Unnamed: 11,2010,536,1373,19486,16956,18600,37835,10329,105115
Unnamed: 12,2011,515,1420,19717,18482,18720,38501,9314,106669
Unnamed: 13,2012,419,1445,20144,19381,19168,42497,8093,111147
Unnamed: 14,2013,335,1378,19128,20297,17429,45368,7400,111335
Unnamed: 15,2014,333,1352,16539,20207,16765,43862,7664,106722
Unnamed: 16,2015,352,1438,16931,20270,15125,44005,7332,105453
Unnamed: 17,2016,335,1438,15500,20847,12990,44279,6327,101716

In [94]:
crime.index = range(17)

In [95]:
del crime.index.name

In [96]:
crime

Seven Major Felony Offenses,Year,MURDER & NON-NEGL. MANSLAUGHTER,RAPE,ROBBERY,FELONY ASSAULT,BURGLARY,GRAND LARCENY,GRAND LARCENY OF MOTOR VEHICLE,TOTAL SEVEN MAJOR FELONY OFFENSES
0,2000,673,2068,32562,25924,38352,49631,35442,184652
1,2001,649,1981,28202,23453,32763,46329,29531,162908
2,2002,587,2144,27229,21147,31275,45771,26656,154809
3,2003,597,2070,25989,19139,29110,46751,23413,147069
4,2004,570,1905,24373,18622,26976,48763,20884,142093
5,2005,539,1858,24722,17750,24117,48243,18246,135475
6,2006,596,1525,23739,17309,23143,46625,15745,128682
7,2007,496,1351,21809,17493,21762,44924,13174,121009
8,2008,523,1299,22401,16284,20725,44242,12482,117956
9,2009,471,1205,18601,16773,19430,39580,10670,106730
10,2010,536,1373,19486,16956,18600,37835,10329,105115
11,2011,515,1420,19717,18482,18720,38501,9314,106669
12,2012,419,1445,20144,19381,19168,42497,8093,111147
13,2013,335,1378,19128,20297,17429,45368,7400,111335
14,2014,333,1352,16539,20207,16765,43862,7664,106722
15,2015,352,1438,16931,20270,15125,44005,7332,105453
16,2016,335,1438,15500,20847,12990,44279,6327,101716

In [100]:
crime.to_csv(os.getenv("PUIDATA")+'/crimedata.csv', encoding='utf-8', index= False)

# Visualize the data using Chernoff face in R


height, width and structure of face: TOTAL.SEVEN.MAJOR.FELONY.OFFENSES 

height,width of mouth: MURDER...NON.NEGL..MANSLAUGHTER 

smiling:RAPE 

height and width of eyes: ROBBERY 

height, width of hair: FELONY.ASSAULT 

style of hair: BURGLARY 

height and width of nose: GRAND.LARCENY 

width and height of ear: GRAND.LARCENY.OF.MOTOR.VEHICLE

# R code

crime <- read.csv('https://raw.githubusercontent.com/gc2300/PUI2017_gc2300/master/HW8_gc2300/crimedata.csv')

head(crime)

system('defaults write org.R-project.R force.LANG en_US.UTF-8')

install.packages("aplpack")

library(aplpack)

crime_field <- cbind(crime[,9],crime[,9],crime[,9],crime[,2],crime[,2],crime[,3],crime[,4],crime[,4],crime[,5],crime[,5],crime[,6],crime[,7],crime[,7],crime[,8],crime[,8])

faces(crime_field, labels=crime$Year)